### PR TITLE
Bug fix for user list

### PR DESCRIPTION
**Pull request by SymphonyOfTranquility**

### CODE REVIEW

**Review by Afohtim — APPROVED** [review]

**Review by Afohtim — CHANGES_REQUESTED** [review]
No

**Review by bfilonenko — APPROVED** [review]

**Review by Afohtim — APPROVED** [review]
YEP

**Review by Afohtim — APPROVED** [review]
Github lag

**Comment by Afohtim** [comment]
What is this pr?

**Pull request merged**
